# Generated by Django 4.2.7 on 2025-11-30 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        db_index=True, verbose_name="IP-адрес"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        db_index=True, max_length=150, verbose_name="Имя пользователя"
                    ),
                ),
                (
                    "attempt_time",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Время попытки"
                    ),
                ),
                (
                    "success",
                    models.BooleanField(default=False, verbose_name="Успешная попытка"),
                ),
                ("user_agent", models.TextField(blank=True, verbose_name="User Agent")),
            ],
            options={
                "verbose_name": "Попытка входа",
                "verbose_name_plural": "Попытки входа",
                "ordering": ["-attempt_time"],
                "indexes": [
                    models.Index(
                        fields=["ip_address", "attempt_time"],
                        name="accounts_lo_ip_addr_34593a_idx",
                    ),
                    models.Index(
                        fields=["username", "attempt_time"],
                        name="accounts_lo_usernam_b60b1c_idx",
                    ),
                ],
            },
        ),
    ]
