# Generated by Django 4.2.7 on 2025-11-30 10:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loginattempt",
            name="attempt_time",
            field=models.DateTimeField(
                db_index=True,
                default=django.utils.timezone.now,
                verbose_name="Время попытки",
            ),
        ),
    ]
