# Generated by Django 5.1.11 on 2026-05-02 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("policies", "0017_remove_policy_premium_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingPeriod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Месяц")),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Активен"), ("archived", "Архив")],
                        default="active",
                        max_length=20,
                        verbose_name="Статус периода",
                    ),
                ),
            ],
            options={
                "verbose_name": "Период очередных взносов",
                "verbose_name_plural": "Периоды очередных взносов",
                "ordering": ["year", "month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="billing_bil_year_86056f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="billing_bil_status_4159f3_idx"
                    ),
                ],
                "unique_together": {("year", "month")},
            },
        ),
        migrations.CreateModel(
            name="BillingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("to_request", "К запросу"),
                            ("requested", "Счет запрошен у СК"),
                            ("sent_to_leasing", "Передан в оплату в лизинговую"),
                        ],
                        db_index=True,
                        default="to_request",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "invoice_request_deadline",
                    models.DateField(verbose_name="Крайняя дата запроса счета"),
                ),
                (
                    "requested_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Счет запрошен"
                    ),
                ),
                (
                    "sent_to_leasing_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Передан в лизинговую"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "payment_schedule",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_task",
                        to="policies.paymentschedule",
                        verbose_name="Платеж",
                    ),
                ),
                (
                    "period",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="billing.billingperiod",
                        verbose_name="Период",
                    ),
                ),
                (
                    "responsible",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ответственный",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача по очередному взносу",
                "verbose_name_plural": "Задачи по очередным взносам",
                "ordering": [
                    "invoice_request_deadline",
                    "payment_schedule__due_date",
                    "id",
                ],
            },
        ),
        migrations.CreateModel(
            name="BillingTaskEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("created", "Создана"),
                            ("status_changed", "Изменен статус"),
                            ("comment_updated", "Обновлен комментарий"),
                            ("synced", "Синхронизирована"),
                        ],
                        max_length=30,
                        verbose_name="Тип события",
                    ),
                ),
                (
                    "old_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Предыдущий статус"
                    ),
                ),
                (
                    "new_status",
                    models.CharField(
                        blank=True, max_length=30, verbose_name="Новый статус"
                    ),
                ),
                ("comment", models.TextField(blank=True, verbose_name="Комментарий")),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="billing.billingtask",
                        verbose_name="Задача",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Событие задачи очередного взноса",
                "verbose_name_plural": "События задач очередных взносов",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="billingtask",
            index=models.Index(fields=["status"], name="billing_bil_status_3844af_idx"),
        ),
        migrations.AddIndex(
            model_name="billingtask",
            index=models.Index(
                fields=["invoice_request_deadline"],
                name="billing_bil_invoice_703f92_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="billingtask",
            index=models.Index(
                fields=["requested_at"], name="billing_bil_request_d92ba2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingtask",
            index=models.Index(
                fields=["sent_to_leasing_at"], name="billing_bil_sent_to_028043_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingtaskevent",
            index=models.Index(
                fields=["event_type"], name="billing_bil_event_t_82a610_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="billingtaskevent",
            index=models.Index(
                fields=["created_at"], name="billing_bil_created_4e4963_idx"
            ),
        ),
    ]
