# Generated by Django 5.1.11 on 2026-05-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingtaskevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("created", "Создана"),
                    ("status_changed", "Изменен статус"),
                    ("synced", "Синхронизирована"),
                ],
                max_length=30,
                verbose_name="Тип события",
            ),
        ),
    ]
