# Generated by Django 5.1.11 on 2026-05-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0002_alter_billingtaskevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("to_request", "Требуется запрос"),
                    ("requested", "Счет запрошен у СК"),
                    ("sent_to_leasing", "Передан в оплату в Альянс"),
                ],
                db_index=True,
                default="to_request",
                max_length=30,
                verbose_name="Статус",
            ),
        ),
    ]
