# Generated by Django 5.1.11 on 2026-05-03 19:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0003_alter_billingtask_status"),
        ("policies", "0017_remove_policy_premium_total"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="billingtask",
            index=models.Index(
                fields=["period", "status"], name="billing_bil_period__64a551_idx"
            ),
        ),
    ]
