# Generated by Django 5.1.11 on 2026-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0004_billingtask_billing_bil_period__64a551_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProlongationBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("year", models.PositiveSmallIntegerField(verbose_name="Год")),
                ("month", models.PositiveSmallIntegerField(verbose_name="Месяц")),
            ],
            options={
                "verbose_name": "Партия пролонгации",
                "verbose_name_plural": "Партии пролонгации",
                "ordering": ["year", "month"],
                "indexes": [
                    models.Index(
                        fields=["year", "month"], name="billing_pro_year_499fec_idx"
                    )
                ],
                "unique_together": {("year", "month")},
            },
        ),
    ]
