# Generated by Django 4.2.7 on 2025-11-22 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=255, verbose_name='Название филиала')),
            ],
            options={
                'verbose_name': 'Филиал',
                'verbose_name_plural': 'Филиалы',
                'ordering': ['branch_name'],
            },
        ),
        migrations.CreateModel(
            name='InfoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Метка')),
            ],
            options={
                'verbose_name': 'Инфо-метка',
                'verbose_name_plural': 'Инфо-метки',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Вид страхования')),
            ],
            options={
                'verbose_name': 'Вид страхования',
                'verbose_name_plural': 'Виды страхования',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Insurer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurer_name', models.CharField(max_length=255, verbose_name='Название страховой компании')),
            ],
            options={
                'verbose_name': 'Страховая компания',
                'verbose_name_plural': 'Страховые компании',
                'ordering': ['insurer_name'],
            },
        ),
        migrations.CreateModel(
            name='CommissionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('kv_percent', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ставка комиссии (%)')),
                ('insurance_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='insurers.insurancetype', verbose_name='Вид страхования')),
                ('insurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rates', to='insurers.insurer', verbose_name='Страховщик')),
            ],
            options={
                'verbose_name': 'Ставка комиссии',
                'verbose_name_plural': 'Ставки комиссий',
                'ordering': ['insurer', 'insurance_type'],
                'unique_together': {('insurer', 'insurance_type')},
            },
        ),
    ]
