# Generated by Django 4.2.7 on 2025-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='contacts',
            field=models.URLField(blank=True, help_text='Ссылка на контакт (например, Telegram, WhatsApp)', verbose_name='Контакты (ссылка)'),
        ),
    ]
