# Generated by Django 4.2.7 on 2025-11-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurers', '0002_insurer_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurer',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечание'),
        ),
    ]
