# Generated by Django 4.2.7 on 2025-11-30 11:51

import apps.core.file_validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurers", "0008_leasingmanager_full_name_alter_leasingmanager_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="branch",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендуемый размер: 200x200px. Разрешены: jpg, jpeg, png (макс. 10MB)",
                null=True,
                upload_to="branch_logos/",
                validators=[apps.core.file_validators.validate_image_file],
                verbose_name="Логотип",
            ),
        ),
        migrations.AlterField(
            model_name="insurancetype",
            name="icon",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендуемый размер: 200x200px. Разрешены: jpg, jpeg, png (макс. 10MB)",
                null=True,
                upload_to="insurance_type_icons/",
                validators=[apps.core.file_validators.validate_image_file],
                verbose_name="Иконка",
            ),
        ),
        migrations.AlterField(
            model_name="insurer",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Рекомендуемый размер: 200x200px. Разрешены: jpg, jpeg, png (макс. 10MB)",
                null=True,
                upload_to="insurer_logos/",
                validators=[apps.core.file_validators.validate_image_file],
                verbose_name="Логотип",
            ),
        ),
    ]
