# Generated by Django 4.2.7 on 2026-04-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurers", "0009_alter_branch_logo_alter_insurancetype_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Широта",
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=9,
                null=True,
                verbose_name="Долгота",
            ),
        ),
    ]
