# Generated by Django 5.1.11 on 2026-05-11 19:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MailAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "code",
                    models.SlugField(max_length=100, unique=True, verbose_name="Код"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Название")),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "display_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Отображаемое имя"
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("smtp", "SMTP")],
                        default="smtp",
                        max_length=50,
                        verbose_name="Провайдер",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активен"),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="По умолчанию"),
                ),
                (
                    "settings_prefix",
                    models.CharField(
                        default="COMMUNICATIONS",
                        max_length=100,
                        verbose_name="Префикс настроек",
                    ),
                ),
            ],
            options={
                "verbose_name": "Почтовый аккаунт",
                "verbose_name_plural": "Почтовые аккаунты",
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["code"], name="communicati_code_a53432_idx"),
                    models.Index(
                        fields=["is_active"], name="communicati_is_acti_5da692_idx"
                    ),
                    models.Index(
                        fields=["is_default"], name="communicati_is_defa_08ac1f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboundEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("billing_insurer_request", "Запрос счета в СК"),
                            ("billing_alliance_forward", "Передача счета в Альянс"),
                        ],
                        max_length=80,
                        verbose_name="Тип письма",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("queued", "В очереди"),
                            ("sending", "Отправляется"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                            ("cancelled", "Отменено"),
                        ],
                        default="draft",
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "from_email",
                    models.EmailField(max_length=254, verbose_name="Отправитель"),
                ),
                (
                    "from_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Имя отправителя"
                    ),
                ),
                (
                    "reply_to",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="Reply-To"
                    ),
                ),
                ("subject", models.CharField(max_length=500, verbose_name="Тема")),
                ("body_text", models.TextField(verbose_name="Текст")),
                ("body_html", models.TextField(blank=True, verbose_name="HTML")),
                (
                    "object_id",
                    models.PositiveIntegerField(verbose_name="ID связанного объекта"),
                ),
                (
                    "queued_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Поставлено в очередь"
                    ),
                ),
                (
                    "sending_started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправка началась"
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Отправлено"
                    ),
                ),
                (
                    "failed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Ошибка отправки"
                    ),
                ),
                (
                    "last_error",
                    models.TextField(blank=True, verbose_name="Последняя ошибка"),
                ),
                (
                    "message_id",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Message-ID"
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="ID письма у провайдера",
                    ),
                ),
                (
                    "headers",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Служебные заголовки"
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_emails",
                        to="communications.mailaccount",
                        verbose_name="Почтовый аккаунт",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип связанного объекта",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_outbound_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создал",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_outbound_emails",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отправил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Исходящее письмо",
                "verbose_name_plural": "Исходящие письма",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EmailDeliveryAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "attempt_number",
                    models.PositiveSmallIntegerField(verbose_name="Номер попытки"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("sending", "Отправляется"),
                            ("sent", "Отправлено"),
                            ("failed", "Ошибка"),
                        ],
                        max_length=30,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Начало"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершение"
                    ),
                ),
                ("error_message", models.TextField(blank=True, verbose_name="Ошибка")),
                (
                    "provider_response",
                    models.TextField(blank=True, verbose_name="Ответ провайдера"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_attempts",
                        to="communications.outboundemail",
                        verbose_name="Письмо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка отправки письма",
                "verbose_name_plural": "Попытки отправки писем",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OutboundEmailAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="communications/outbound/%Y/%m/", verbose_name="Файл"
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(max_length=255, verbose_name="Исходное имя файла"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="MIME-тип"
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0, verbose_name="Размер")),
                (
                    "checksum",
                    models.CharField(blank=True, max_length=64, verbose_name="SHA-256"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="communications.outboundemail",
                        verbose_name="Письмо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вложение исходящего письма",
                "verbose_name_plural": "Вложения исходящих писем",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OutboundEmailRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "recipient_type",
                    models.CharField(
                        choices=[
                            ("to", "Кому"),
                            ("cc", "Копия"),
                            ("bcc", "Скрытая копия"),
                        ],
                        default="to",
                        max_length=10,
                        verbose_name="Тип получателя",
                    ),
                ),
                ("address", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "name",
                    models.CharField(blank=True, max_length=255, verbose_name="Имя"),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="communications.outboundemail",
                        verbose_name="Письмо",
                    ),
                ),
            ],
            options={
                "verbose_name": "Получатель письма",
                "verbose_name_plural": "Получатели писем",
                "ordering": ["recipient_type", "address"],
            },
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(fields=["status"], name="communicati_status_8928bf_idx"),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(fields=["kind"], name="communicati_kind_14ac76_idx"),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["created_at"], name="communicati_created_fc254c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["sent_at"], name="communicati_sent_at_e4629f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="communicati_content_128150_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemail",
            index=models.Index(
                fields=["message_id"], name="communicati_message_ea46cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryattempt",
            index=models.Index(
                fields=["email", "attempt_number"],
                name="communicati_email_i_0a0673_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryattempt",
            index=models.Index(fields=["status"], name="communicati_status_d86fd2_idx"),
        ),
        migrations.AddIndex(
            model_name="emaildeliveryattempt",
            index=models.Index(
                fields=["created_at"], name="communicati_created_050e47_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemailattachment",
            index=models.Index(
                fields=["checksum"], name="communicati_checksu_4b2d6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemailrecipient",
            index=models.Index(
                fields=["email", "recipient_type"],
                name="communicati_email_i_c8374d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="outboundemailrecipient",
            index=models.Index(
                fields=["address"], name="communicati_address_b5067c_idx"
            ),
        ),
    ]
