# Generated by Django 5.1.11 on 2026-05-12 11:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="outboundemail",
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("send_outbound_email", "Может отправлять письма из системы")
                ],
                "verbose_name": "Исходящее письмо",
                "verbose_name_plural": "Исходящие письма",
            },
        ),
    ]
