# Generated by Django 5.1.11 on 2026-06-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communications", "0003_outboundemail_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundemail",
            name="kind",
            field=models.CharField(
                choices=[
                    ("billing_insurer_request", "Запрос счета в СК"),
                    ("billing_alliance_forward", "Передача счета в Альянс"),
                    ("prolongation_forward", "Пролонгация — таблица договоров"),
                ],
                max_length=80,
                verbose_name="Тип письма",
            ),
        ),
    ]
