# Generated by Django 4.2.7 on 2025-11-28 10:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_migrate_leasing_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='broker_participation',
            field=models.BooleanField(default=True, verbose_name='Участие брокера'),
        ),
        migrations.AddField(
            model_name='policy',
            name='property_year',
            field=models.IntegerField(blank=True, help_text='Год выпуска застрахованного имущества (1900-2100)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Год выпуска имущества'),
        ),
    ]
