# Generated by Django 4.2.7 on 2025-11-28 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_notes'),
        ('policies', '0008_policy_broker_participation_policy_property_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policyholder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policyholder_policies', to='clients.client', verbose_name='Страхователь'),
        ),
    ]
