# Generated by Django 4.2.7 on 2025-11-28 17:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0009_alter_policy_policyholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="termination_date",
            field=models.DateField(
                blank=True,
                help_text="Дата досрочного расторжения полиса",
                null=True,
                verbose_name="Дата расторжения",
            ),
        ),
    ]
