# Generated by Django 4.2.7 on 2025-12-03 20:32

from django.db import migrations


def remove_duplicate_payments(apps, schema_editor):
    """
    Remove duplicate payment schedules keeping only the latest created one.
    """
    from django.db.models import Count

    PaymentSchedule = apps.get_model("policies", "PaymentSchedule")

    # Find all duplicates
    duplicates = (
        PaymentSchedule.objects.values("policy_id", "year_number", "installment_number")
        .annotate(count=Count("id"))
        .filter(count__gt=1)
    )

    deleted_count = 0
    for dup in duplicates:
        # Get all records with this combination
        records = PaymentSchedule.objects.filter(
            policy_id=dup["policy_id"],
            year_number=dup["year_number"],
            installment_number=dup["installment_number"],
        ).order_by("-created_at")

        # Keep the first (latest), delete the rest
        records_to_delete = records[1:]
        for record in records_to_delete:
            record.delete()
            deleted_count += 1

    if deleted_count > 0:
        print(f"Removed {deleted_count} duplicate payment schedule records")


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0010_add_termination_date"),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_payments, migrations.RunPython.noop),
    ]
