# Generated by Django 4.2.7 on 2025-12-03 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0011_remove_duplicate_payments"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="paymentschedule",
            unique_together={("policy", "year_number", "installment_number")},
        ),
    ]
