# Generated by Django 4.2.7 on 2025-12-05 17:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0012_alter_paymentschedule_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentschedule",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                verbose_name="Страховая премия",
            ),
        ),
    ]
