# Generated by Django 4.2.7 on 2025-12-16 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0013_change_amount_verbose_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="vin_number",
            field=models.CharField(
                blank=True,
                help_text="VIN номер транспортного средства (17 символов, латинские буквы кроме I, O, Q и цифры)",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_vin",
                        message="VIN номер должен состоять из 17 символов, включающих буквы латинского алфавита (кроме I, O, Q) и цифры",
                        regex="^[A-HJ-NPR-Z0-9]{17}$",
                    )
                ],
                verbose_name="VIN номер",
            ),
        ),
    ]
