# Generated by Django 4.2.7 on 2025-12-18 18:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0014_policy_vin_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policy",
            name="vin_number",
            field=models.CharField(
                blank=True,
                help_text="Идентификатор транспортного средства (3-17 символов, латинские буквы и цифры)",
                max_length=17,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalid_identifier",
                        message="Идентификатор должен состоять из 3-17 символов, включающих латинские буквы и цифры",
                        regex="^[A-Z0-9]{3,17}$",
                    )
                ],
                verbose_name="Идентификатор (обычно VIN)",
            ),
        ),
    ]
