# Generated by Django 4.2.7 on 2025-12-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0015_alter_policy_vin_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentschedule",
            name="insurer_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата согласования акта с СК"
            ),
        ),
    ]
