# Generated by Django 5.1.11 on 2026-04-25 16:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0016_update_insurer_date_verbose_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="policy",
            name="premium_total",
        ),
    ]
