# Generated by Django 5.1.11 on 2026-05-03 19:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurers", "0010_branch_add_coordinates"),
        ("policies", "0017_remove_policy_premium_total"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="paymentschedule",
            index=models.Index(
                fields=["paid_date", "due_date"], name="policies_pa_paid_da_4940dc_idx"
            ),
        ),
    ]
