# Generated by Django 5.1.11 on 2026-06-08 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("policies", "0020_paymentschedule_alliance_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="dfa_deactivation_date",
            field=models.DateField(
                blank=True,
                help_text="Дата, с которой ДФА перестал быть активным. Очередные взносы с датой платежа после этой даты не попадают на страницу и в экспорт «Очередные взносы».",
                null=True,
                verbose_name="Дата деактивации ДФА",
            ),
        ),
    ]
