# Generated by Django 4.2.7 on 2025-11-23 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True, verbose_name="Примечание"),
        ),
    ]
