# Generated by Django 4.2.7 on 2025-12-03 20:15

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_inn',
            field=models.CharField(blank=True, help_text='ИНН должен содержать 10 или 12 цифр', max_length=12, null=True, unique=True, validators=[apps.clients.models.validate_inn], verbose_name='ИНН'),
        ),
    ]
