# Generated by Django 4.2.7 on 2025-12-05 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("clients", "0003_alter_client_client_inn"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="alternative_name",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Альтернативное название",
            ),
        ),
    ]
