# Generated by Django 5.1.11 on 2026-04-25 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customexporttemplate",
            name="data_source",
            field=models.CharField(
                choices=[("policies", "Полисы"), ("payments", "Платежи")],
                max_length=50,
                verbose_name="Источник данных",
            ),
        ),
    ]
